# Generated by Django 4.0.1 on 2022-03-10 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=30)),
                ('DOB', models.DateField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
                ('qualification', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('cv', models.FileField(null=True, upload_to='files')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=15)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobs')),
            ],
        ),
    ]
