# Generated by Django 4.0.1 on 2022-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_applications_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='submitted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
